### ISSUE TITLE
Make instructions more precise on what they expect

### ISSUE THREAD

**Issue by mpas97** [exercism/elixir#884] opened 2021-09-06 12:49 UTC
Exercise instructions are often very unclear / unspecific. For `Acronym` this is the whole thing we get:
![grafik](https://user-images.githubusercontent.com/9994218/132216039-c3c17eb5-f1a2-4e5e-8908-3c68a7768fd9.png)

So I would expect that something like this would do it:
`string |> String.split |> Enum.map(&(String.first(&1))) |> Enum.join |> String.upcase`
but instead I always have to do dozens of "try and error" as the tests expect:
- `Metal-Oxide` -> `MO`
- `Something - I` -> `SI`
- `The Road _Not_ Taken` -> `TRNT`
or even things like respecting camel case:
- `HyperText` -> `HT`

So in this exercise, for instance, it would make much sense to explain what characters are expected to be ignored and which should act as spliters. And we should mention that a case change should also trigger the split. We shoudn't have to reverse engineer from the tests to understand an exercise.

**Comment by verdammelt** [comment] 2021-09-06 12:54
Not an elixir track person but this description is the 'standard' one from the [problem specifications repo](https://github.com/exercism/problem-specifications) which many tracks use as the genesis of these exercises. If that is the case with elixir then we should probably actually move this issue to the problem specifiations repository as the change would need to be made there.

**Comment by jiegillet** [comment] 2021-09-06 12:59
That's right, we try to follow the specifications closely. If the specifications change, we will follow.

On personal note, I agree with you, I don't like this exercise much either, it's edge cases after edge cases, and all kind of arbitrary. That's what real life problems are for ;)

**Comment by mpas97** [comment] 2021-09-06 13:00
@verdammelt Thanks! The description is indeed very short there too, but eg. the mixed-case test has already been removed 4 years ago: https://github.com/exercism/problem-specifications/commit/cae7ae184caf9adb08525077d5b2a8e60f844417

**Comment by jiegillet** [comment] 2021-09-06 13:06
Well, I said we would follow, we should follow then :)
@mpas97, care to do the honors?

**Comment by angelikatyborska** [comment] 2021-09-06 13:06
> We shoudn't have to reverse engineer from the tests to understand an exercise.

I'm afraid that is exactly what you need to do for almost every practice exercise on Exercism, in every track. The descriptions are almost all very general and shared for all tracks so they cannot include track-specific details, and it's always the tests that specify corner cases. But if it's necessary, we can append track-specific content to the instructions via an extra `instructions.append.md` file.

> but eg. the mixed-case test has already been removed 4 years ago: exercism/problem-specifications@cae7ae1

We should probably re-review this exercise then and make sure there are no extra test cases compared to problem specifications.

@neenjaw you were the one that decided to keep this test for "HTML". (see https://github.com/exercism/elixir/commit/9f8c442682ff18c5a2effee92ab4d0f43d991ba2#diff-3e97097f94e9b901afd064e75173ea6d0278ccee27e68edec52ed608c2ff3545R50). Would you have anything against removing it?

**Comment by jiegillet** [comment] 2021-09-06 13:11
I hope I didn't speak too soon :p
In any case we can keep discussing around a PR. 

> We should probably re-review this exercise then and make sure there are no extra test cases compared to problem specifications.

HTML is the only difference with the canonical data.

**Comment by SleeplessByte** [comment] 2021-09-06 15:52
FWIW, on JS / TS, we have a few practice exercises with inserts for exactly this reason. But yes, it's "By Design".

**Comment by jiegillet** [comment] 2021-09-11 00:35
Closed via #885. Thank you.

**Closed by jiegillet** 2021-09-11 00:35 UTC
