### ISSUE TITLE
Undisclosed reason for failing test when local tests pass

### ISSUE THREAD

**Issue by justin-m-morgan** [exercism/elixir#1014] opened 2021-11-26 17:32 UTC
I recently submitted a challenge solution that had all the local tests passing but upon uploading my solution I received the following message: 

```
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```

I did several submission to test if it was a one off, but each iteration returned the same error.

This was for the challenge "Palindrome Products" and the challenge submission in question [can be viewed here](https://exercism.org/tracks/elixir/exercises/palindrome-products/solutions/justin-m-morgan)

**Comment by angelikatyborska** [comment] 2021-11-26 17:59
Thank you for reporting! There is something suspicious going on here. After taking a look for 10 minutes, I think there is a serious bug in the Elixir test runner (https://github.com/exercism/elixir-test-runner).

At first I thought it might have something to do with the slow tests - there are two tests tagged as slow, and the whole test suite takes 20 seconds to run with those slow tests (that would trigger a timeout). But I am pretty certain excluding slow tests works correctly, otherwise we would have gotten complaints about other exercises too. There is a unit test for that as well, so I don't think that's it.

I think the issue is with the transformations we do on the test file before we run it. The transformed test for this exercise includes this invalid syntax:
```elixir
assert(palindromes'y' == ['\v\v'])
# original: assert palindromes[9009] == [[91, 99]]
```

The bug must have been there for a while. There are other published community solutions failing:
- https://exercism.org/tracks/elixir/exercises/palindrome-products/solutions/rhokappa
- https://exercism.org/tracks/elixir/exercises/palindrome-products/solutions/borski
- 
Actually, there might be no community solutions with passing tests for this exercise...

**Comment by angelikatyborska** [comment] 2021-11-26 18:11
Yeah - this is an Elixir bug that will be fixed in 1.13 (I have a release candidate compiled locally so I verified this on my own). Until then, we need to come up with a fix.

```elixir
code =
~S'''
map = %{66 => :foo, 67 => :bar}
map[66]
'''

ast = Code.string_to_quoted!(code)
Macro.to_string(ast) 

# 1.12 result
"(\n  map = %{66 => :foo, 67 => :bar}\n  map'B'\n)"

# 1.13 result
"map = %{66 => :foo, 67 => :bar}\nmap[66]"

**Comment by justin-m-morgan** [comment] 2021-11-26 18:57
Okay, so no steps needed to take then? Just close this?

**Comment by jiegillet** [comment] 2021-11-27 01:32
No please don’t close this, 1.13 is probably coming soon (rc1 is out I think) but we should still fix this. 
I’m guessing we should be able to format the test file differently so that the parser doesn’t get confused

**Comment by justin-m-morgan** [comment] 2021-11-27 01:39
I deleted my comment, I wrote it with the first part of the response off-screen. 😊

**Comment by angelikatyborska** [comment] 2021-11-27 10:49
`Macro.to_string` allows passing a function as a second argument that can modify the output string. We could use that to patch this corner case, something like this:

```elixir
ast = Code.string_to_quoted!("foo[66]")
Macro.to_string(ast, fn node, string ->
  if is_list(node) and Enum.all?(node, &Kernel.is_integer/1) do
    inspect(node, charlists: :as_lists)
  else
    string
  end
end)
```

**Comment by jiegillet** [comment] 2021-11-27 12:08
I checked all exercises for this issue (by running the exemploid solution through the test runner), and `palindrome-products` is not the only one, there is also `forth`:

```elixir
Forth.eval("1\x002\x013\n4\r5 6\t7") # before transformation
Forth.eval(<<49, 0, 50, 1, 51, 92, 110, 52, 13, 53, 225, 154, 128, 54, 9, 55>>) # after transformation
```
The issue is with the escaped characters.

**Comment by jiegillet** [comment] 2021-11-27 12:35
Well, actually, that seems to be a different bug. The reason for this is the `TestSource.Transformer.escape_newlines/1` function is modifying the string, but `TestSource.Transformer. unescape_final_newlines/1` is not bringing it back to its original form because the string is printed in its special form `<<>>` instead of being printed as a string with newline...

I'm pretty sure this would also go away with 1.13 as well. 
Is using 1.13.rc-1 completely out of the question? 😄

**Comment by angelikatyborska** [comment] 2021-11-27 14:30
I would not use a release candidate, not because I don't trust it, but because the students wouldn't be able to use the same version in the same ways they update to official releases.

Do we know when 1.13 is scheduled to be released officially? Maybe we can just wait it out.

**Comment by jiegillet** [comment] 2021-11-29 06:39
I couldn't find when 1.13 will come out, and I don't think I could leave an issue like this one open for an unknown period of time, so I send a [fix for the issues](https://github.com/exercism/elixir-test-runner/pull/73). The fix is not pretty, kind of on purpose to remind me to switch to 1.13 ASAP 😸

**Comment by jiegillet** [comment] 2021-11-30 05:30
@justin-m-morgan, the problem has been fixed, please try again to submit your solution.
Thank you very much for submitting this issue, on top of fixing your problem it prompted us to make the test-runner internal test suite much more robust.

**Closed by jiegillet** 2021-11-30 05:30 UTC
