### ISSUE TITLE
markdown: Elixir given code does not follow the specification/given documentation

### ISSUE THREAD

**Issue by rpottsoh** [exercism/elixir#449] opened 2019-02-05 20:08 UTC
@Sayrus commented on [Tue Feb 05 2019](https://github.com/exercism/problem-specifications/issues/1455)

The given implementation does not follow the Markdown specification nor does it follows the expected output given in the code comments. The purpose of the exercise is to refactor, after reading #271, I do think this should be fixed.

Header parsing rely on split to get the current header level:
```
iex(1)> Markdown.parse("#Test")
"<h5></h5>"
iex(2)> Markdown.parse("# Test")
"<h1>Test</h1>"
iex(3)> Markdown.parse("#I_am_a_very_large header")
"<h18>header</h18>"
```
List doesn't work any better:

```
iex(1)> Markdown.parse("* Test")
"<ul><li>Test</li></ul>"
iex(2)> Markdown.parse("*Test") 
"<ul><li>*Test</li></ul>"
```

And the real problem as the others could just be on purpose. According to the comment given in the code:
```
iex> Markdown.parse("#Header!\n* __Bold Item__\n* _Italic Item_")
"<h1>Header!</h1><ul><li><em>Bold Item</em></li><li><i>Italic Item</i></li></ul>"
```

Reality when using the ref:
```
iex(7)> Markdown.parse("#Header!\n* __Bold Item__\n* _Italic Item_")
"<h8></h8><ul><li><strong>Bold Item</strong></li><li><em>Italic Item</em></li></ul>"
```

---

@rpottsoh commented on [Tue Feb 05 2019](https://github.com/exercism/problem-specifications/issues/1455#issuecomment-460724769)

Without performing any deeper investigating, it seems to me that this is an issue for the @exercism/elixir maintainers to look into and should be moved to the [Elixer](https://github.com/exercism/elixir/issues) repo.

---

@Sayrus commented on [Tue Feb 05 2019](https://github.com/exercism/problem-specifications/issues/1455#issuecomment-460776577)

You're right, I missed this repo. I'll wait for an repo admin to move it as I don't want to create a duplicate.

**Comment by Sayrus** [comment] 2019-02-09 15:27
String.replace_suffix/3 won't work as intended if a list ends before the end of the string.
```
iex(9)> Markdown.parse("* First elem\n Paragraph \n* First elem")
"<ul><li>First elem</li><p>Paragraph</p><li>First elem</li></ul>"
```

**Comment by devonestes** [comment] 2019-02-11 15:45
@Sayrus I would gladly accept a PR that adds more tests and fixes the current implementation.

That said, the point of the exercise is to refactor, so as long as the tests are green, then _technically_ the learner is refactoring. If the exercise they're refactoring isn't totally complete that isn't actually so important, but it's always better to be very complete if we can be!

**Comment by Sayrus** [comment] 2019-02-11 15:56
@devonestes I will provide a simple PR to correct the doctest. I am currently following the Elixir course so I am not confident enough to provide a good teaching code.

**Comment by devonestes** [comment] 2019-02-11 15:59
@Sayrus I'll be happy to help! The best part is the code in this exercise should _intentionally_ be bad, so no worries about trying to write proper Elixir. As long as the tests pass, that's all that matters.

**Comment by Sayrus** [comment] 2019-02-20 09:30
@devonestes Understood. Here is the PR to match the doctest with the given code: #450.

**Comment by angelikatyborska** [comment] 2021-02-27 16:35
More tests for Markdown were added in: https://github.com/exercism/elixir/pull/628

I opened https://github.com/exercism/elixir/pull/676 that fixes the code example

**Comment by angelikatyborska** [comment] 2021-02-28 15:59
The code example fix was merged to `main` in this PR https://github.com/exercism/elixir/pull/677 that adds a step to the CI check that all doctests in example solutions are actually correct.

**Closed by angelikatyborska** 2021-02-28 15:59 UTC
